FROM confluentinc/cp-kafka-connect-base:latest

# Copy the Snowflake Kafka connector JAR file
COPY snowflake-kafka-connector-3.0.0.jar /usr/share/java/snowflake-kafka-connector/snowflake-kafka-connector-3.0.0.jar


